### ISSUE TITLE
vim.sexy is down

### ISSUE THREAD

**Issue by jankeromnes** [worr/vim.sexy#3]
Currently, going to https://vim.sexy or http://vim.sexy gives a CloudFlare `Error 521` page saying that `Web server is down`.

If the web server can't be fixed, is it possible to push this to the `gh-pages` page, and add a `CNAME` flie to this repository / point the DNS to GitHub so that GitHub can be the host?

**Comment by worr** [comment]
It's up now. I'd prefer to keep the email service running, which involves keeping the golang portion around. I could switch to some nifty frontend one, but that may cost money, and I lose the exclusivity of the invites.
